version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    volumes:
      - ./.docker/data/dynamodb:/home/dynamodblocal/data
    ports:
      - 8002:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"